ALTER TABLE jobs ADD COLUMN IF NOT EXISTS colour VARCHAR(30) NOT NULL DEFAULT 'Unknown';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS started_at TIMESTAMP;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS paused_at TIMESTAMP;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS paused_duration_seconds BIGINT NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS progress_percent INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS remaining_seconds BIGINT NOT NULL DEFAULT 0;
