; generated by PrusaSlicer 2.8.1 on 2026-09-01 at 11:05:00 UTC
;
; *** EXPORT SETTINGS REMINDER ***
; This file was exported with binary G-code DISABLED.
; PrusaSlicer setting: Output Options → Binary G-code → unchecked
;
; --- Machine settings ---
; printer_model = XL
; printer_variant = 0.4
; printer_settings_id = Prusa XL 0.4 nozzle
; nozzle_diameter = 0.4
;
; *** INTENTIONALLY INVALID FOR CORE ONE COMPATIBILITY TEST ***
; This file was sliced for the Prusa XL (360×360×360 mm) but the
; acceptance test selects "PRUSA_CORE_ONE" (250×220×270 mm).
; Expected validation failures:
;   1. Printer profile mismatch: PRUSA_XL != PRUSA_CORE_ONE
;   2. Print volume exceeds Core One X-axis: 310 mm > 250 mm max
;   3. Print volume exceeds Core One Y-axis: 280 mm > 220 mm max
;
; --- Print profile settings ---
; layer_height = 0.20
;
; --- Filament settings ---
; filament_type = PLA
; temperature = 215
; bed_temperature = 60
;
; --- Print dimensions (bounding box) ---
; print_dimensions_x = 310.00
; print_dimensions_y = 280.00
; print_dimensions_z = 50.00
;
; --- Estimated cost data ---
; total weight = 45.80
; estimated printing time (normal mode) = 3h 12m 0s
;
; --- End of header ---
G28
M83
G1 Z0.250 F900
; (toolpath omitted)
M104 S0
M140 S0
M84
