; generated by PrusaSlicer 2.8.1 on 2026-09-01 at 10:23:15 UTC
;
; *** EXPORT SETTINGS REMINDER ***
; This file was exported with binary G-code DISABLED.
; PrusaSlicer setting: Output Options → Binary G-code → unchecked
;
; --- Machine settings ---
; printer_model = XL
; printer_variant = 0.4
; printer_settings_id = Prusa XL 0.4 nozzle
; nozzle_diameter = 0.4
; max_print_height = 360
;
; --- Print profile settings ---
; layer_height = 0.20
; first_layer_height = 0.25
; perimeters = 3
; fill_density = 15%
; fill_pattern = gyroid
;
; --- Filament settings ---
; filament_type = PLA
; filament_vendor = Prusament
; temperature = 215
; bed_temperature = 60
; first_layer_temperature = 215
; first_layer_bed_temperature = 65
;
; --- Print dimensions (bounding box) ---
; print_dimensions_x = 125.30
; print_dimensions_y = 98.45
; print_dimensions_z = 42.00
;
; --- Estimated cost data ---
; total weight = 18.62
; total filament used [cm3] = 17.74
; estimated printing time (normal mode) = 1h 23m 45s
;
; --- End of header ---
M73 P0 R84
M73 Q0 S84
M201 X1000 Y1000 Z200 E5000
M203 X200 Y200 Z12 E120
M204 P1250 R1250 T2500
M205 X8 Y8 Z0.4 E1.5
M107
M900 K0.05
T0
G28
G29
M83
; --- Toolpath starts here ---
G1 Z0.250 F900
G1 X60.879 Y72.843 F9000
G1 E1.04 F3600
G1 X61.125 Y72.843 E0.00978
G1 X61.125 Y131.157 E2.32044
G1 X60.879 Y131.157 E0.00978
G1 X60.879 Y72.843 E2.32044
; (... additional toolpath omitted for brevity ...)
M104 S0
M140 S0
M107
G28 X0
M84
